tinyMCE.addI18n('el.advanced',{
style_select:"Στύλ",
font_size:"Μέγεθος γραμματοσειράς",
fontdefault:"Τύπος γραμματοσειράς",
block:"Φορμά",
paragraph:"Παράγραφος",
div:"Div",
address:"Διεύθυνση",
pre:"Προ-μορφοποιημένο",
h1:"Κεφαλίδα 1",
h2:"Κεφαλίδα 2",
h3:"Κεφαλίδα 3",
h4:"Κεφαλίδα 4",
h5:"Κεφαλίδα 5",
h6:"Κεφαλίδα 6",
blockquote:"Blockquote",
code:"Κώδικας",
samp:"Δείγμα κώδικα",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"Έντονη γραφή (Ctrl+B)",
italic_desc:"Πλάγια γραφή (Ctrl+I)",
underline_desc:"Υπογράμμιση (Ctrl+U)",
striketrough_desc:"Υπογράμμιση στο κέντρο",
justifyleft_desc:"Στοίχιση αριστερά",
justifycenter_desc:"Στοίχιση κέντρο",
justifyright_desc:"Στοίχιση δεξιά",
justifyfull_desc:"Πλήρη στοίχηση",
bullist_desc:"Μη αριθμημένη λίστα",
numlist_desc:"Αριθμημένη λίστα",
outdent_desc:"Εσοχή δεξιά",
indent_desc:"Εσοχή αριστερά",
undo_desc:"Αναίρεση (Ctrl+Z)",
redo_desc:"Ακύρωση της αναίρεσης (Ctrl+Y)",
link_desc:"Εισαγωγή/Επεξεργασία συνδέσμου",
unlink_desc:"Κατάργηση συνδέσμου",
image_desc:"Εισαγωγή/Επεξεργασία εικόνας",
cleanup_desc:"Καθάρισμα άχρηστου κώδικα",
code_desc:"Επεξεργασία κώδικα HTML",
sub_desc:"Δείκτης",
sup_desc:"Εκθέτης",
hr_desc:"Εισαγωγή οριζόντιας γραμμής",
removeformat_desc:"Διαγραφή μορφοποίησης",
custom1_desc:"Η δική σας περιγραφή εδώ",
forecolor_desc:"Επιλέξετε χρώμα γραφής",
backcolor_desc:"Επιλέξτε χρώμα υπόβαθρου",
charmap_desc:"Εισαγωγή custom χαρακτήρου",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Εισαγωγή/Επεξεργασία άγκυρας",
cut_desc:"Αποκοπή",
copy_desc:"Αντιγραφή",
paste_desc:"Επικολληση",
image_props_desc:"Ιδιότητες εικόνες",
newdocument_desc:"Νέο έγγραφο",
help_desc:"Βοήθεια",
blockquote_desc:"Επισύμανση",
clipboard_msg:"Η Αντιγραφή/Αποκοπή/Επικόλληση δεν είναι διαθέσιμη στον Mozilla and Firefox.\r\nΘέλετε να δείτε περισσότερες πληροφορίες σχετικά με αυτό?",
path:"Διαδρομή",
newdocument:"Είστε βέβαιος ότι θέλετε να διαγράψετε όλα τα περιεχόμενα?",
toolbar_focus:"Εργλαειοθήκη - Alt+Q, Επεξεργαστής κειμένου - Alt-Z, Διαδρομή στοιχείου - Alt-X",
more_colors:"Περισσότερα χρώματα"
});