tinyMCE.addI18n('el.advanced_dlg',{
about_title:"Σχτικά με το TinyMCE",
about_general:"Σχετικά",
about_help:"Βοήθεια",
about_license:"Άδεια",
about_plugins:"Προσαρτήσεις",
about_plugin:"Προσάρτηση",
about_author:"Συγγραφέας",
about_version:"Έκδοση",
about_loaded:"Φορτωμένες προσαρτήσεις",
anchor_title:"Εισαγωγή/Επεξεργασία άγκυρας",
anchor_name:"Ονομασία άγκυρας",
code_title:"Επεξεργαστής κώδικα HTML",
code_wordwrap:"Αναδίπλωση λέξεων",
colorpicker_title:"Επιλέξτε χρώμα",
colorpicker_picker_tab:"Επιλογέας",
colorpicker_picker_title:"Επιλογέας χρώματος",
colorpicker_palette_tab:"Παλέτα",
colorpicker_palette_title:"Χρώματα παλέτας",
colorpicker_named_tab:"Ονομασία",
colorpicker_named_title:"Ονομασία χρωμάτων",
colorpicker_color:"Χρώμα:",
colorpicker_name:"Όνομα:",
charmap_title:"Επιλογή custom χαρακτήρα",
image_title:"Εισαγωγή/Επεξεργασία εικόνας",
image_src:"URL εικόνας",
image_alt:"Περιγραφή εικόνας",
image_list:"Λίστα εικόνων",
image_border:"Πλαίσιο",
image_dimensions:"Διαστάσεις",
image_vspace:"Κάθετο κενό",
image_hspace:"Οριζόντιο κενό",
image_align:"Στοίχιση",
image_align_baseline:"Γραμμή βάσης",
image_align_top:"Επάνω",
image_align_middle:"Μέση",
image_align_bottom:"Κάτω",
image_align_texttop:"Κείμενο επάνω",
image_align_textbottom:"Κείμενο κάτω",
image_align_left:"Αριστερά",
image_align_right:"Δεξιά",
link_title:"Εισαγωγή/Επεξεργασία συνδέσμου",
link_url:"URL συνδέσμου",
link_target:"Στόχος",
link_target_same:"Άνοιγμα του συνδέσμου στο ίδιο παράθυρο",
link_target_blank:"Άνοιγμα του συνδέσμου σε νέο παράθυρο",
link_titlefield:"Τίτλος",
link_is_email:"Η διεύθυνση που εισάγατε μοιάζει να είναι διεύθυνση ηλεκτρονικού ταχυδρομείου. Θέλετε να βάλω μπροστά το πρόθεμα mailto: ?",
link_is_external:"Η διεύθυνση που εισάγατε μοιάζει να είναι εξωτερική διεύθυνση σε κάποια ιστοσελίδα. Θέλετε να βάλω μπροστά το πρόθεμα http:// ?",
link_list:"Λίστα συνδέσμων"
});