tinyMCE.addI18n('el.fullpage_dlg',{
title:"Ιδιότητες εγγράφου",
meta_tab:"Γενικά",
appearance_tab:"Εμφάνιση",
advanced_tab:"Προηγμένο",
meta_props:"Meta πληροφορίες",
langprops:"Γλώσσα και κωδικοποίηση",
meta_title:"Τίτλος",
meta_keywords:"Λέξεις κλειδιά",
meta_description:"Περιγραφή",
meta_robots:"Ρομπότ",
doctypes:"Τύπος εγγράφου",
langcode:"Κωδικός γλώσσας",
langdir:"Κατεύθυνση κειμένου",
ltr:"Αριστερά προς δεξιά",
rtl:"Δεξιά προς αριστερά",
xml_pi:"Δήλωση XML",
encoding:"Κωδικοποίηση χαρακτήρων",
appearance_bgprops:"Ιδιότητες υπόβαθρου",
appearance_marginprops:"Περιθώρια σώματος κειμένου",
appearance_linkprops:"Σύνδεση χρωμάτων",
appearance_textprops:"Ιδιότητες κειμένου",
bgcolor:"Χρώμα υπόβαθρου",
bgimage:"Εικόνα υπόβαθρου",
left_margin:"Αριστερό περιθώριο",
right_margin:"Δεξί περιθώριο",
top_margin:"Επάνω περιθώριο",
bottom_margin:"Κάτω περιθώριο",
text_color:"Χρώμα κειμένου",
font_size:"Μέγεθος γραμματοσειράς",
font_face:"Τύπος γραμματοσειράς",
link_color:"Χρώμα συνδέσμου",
hover_color:"Χρώμα ενεργής επιλογής συνδέσμου (hover)",
visited_color:"Χρώμα συνδέσμου μετά από μετάβαση (visited)",
active_color:"Ενεργό χρώμα",
textcolor:"Χρώμα",
fontsize:"Μέγεθος γραμματοσειράς",
fontface:"Τύπος γραμματοσειράς",
meta_index_follow:"Ευρετηρίασε και ακολούθησε τους συνδέσμους",
meta_index_nofollow:"Ευρετηρίασε αλλά μην ακολουθήσεις τους συνδέσμους",
meta_noindex_follow:"Μην ευρετηριάσεις αλλά ακολούθησε τους συνδέσμους",
meta_noindex_nofollow:"Μην ευρετηριάσεις και μην ακολουθήσεις τους συνδέσμους",
appearance_style:"Στύλ σελίδας και ιδιότητες",
stylesheet:"Στύλ σελίδας",
style:"Στύλ",
author:"Συγγραφέας",
copyright:"Copyright",
add:"Προσθήκη νέου στοιχείου",
remove:"Διαγραφή του επιλεγμένου στοιχείου",
moveup:"Μετακίνηση του επιλεγμένου στοιχείου επάνω",
movedown:"Μετακίνηση του επιλεγμένου στοιχείου κάτω",
head_elements:"Στοιχεία κεφαλίδας",
info:"Πληροφορίες",
add_title:"Τίτλος στοιχείου",
add_meta:"Meta στοιχείο",
add_script:"Στοιχείο σεναρίου (script)",
add_style:"Στοιχείο στύλ",
add_link:"Στοιχείο συνδέσμου",
add_base:"Στοιχείο βάσης",
add_comment:"Κόμβος σχολίων",
title_element:"Στοιχείο τίτλου",
script_element:"Στοιχείο σεναρίου (script)",
style_element:"Στοιχείο στύλ",
base_element:"Στοιχείο βάσης",
link_element:"Στοιχείο συνδέσμου",
meta_element:"Meta στοιχείο",
comment_element:"Σχόλιο",
src:"src",
language:"Γλώσσα",
href:"Href",
target:"Target",
type:"Type",
charset:"Charset",
defer:"Defer",
media:"Media",
properties:"Properties",
name:"Name",
value:"Value",
content:"Content",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Γενικά",
advanced_props:"Προηγμένο"
});