tinyMCE.addI18n('el.advlink_dlg',{
title:"Εισαγωγή/Επεξεργασία συνδέσμου",
url:"URL συνδέσμου",
target:"Στόχος",
titlefield:"Τίτλος",
is_email:"Το URL που εισαγάγατε μοιάζει με διεύθυνση ηλεκτρονικού ταχυδρομείου. Θέλετε να προσθέσω το πρόθεμα mailto: ?",
is_external:"Το URL που εισαγάγατε μοιάζει με εξωτετική διεύθυνση κάποιας ιστοσελίδας. Θέλετε να προσθέσω το πρόθεμα http:// ?",
list:"Λίστα συνδέσμων",
general_tab:"Γενικά",
popup_tab:"Popup",
events_tab:"Γεγονότα",
advanced_tab:"Για προχωρημένους",
general_props:"Ιδιότητες γενικών ρυθμίσεων",
popup_props:"Ιδιότητες Popup",
event_props:"Γεγονότα",
advanced_props:"Ιδιότητες προχωρημένων ρυθμίσεων",
popup_opts:"Επιλογές",
anchor_names:"Σύνδεσμοι σε ετικέτες",
target_same:"Άνοιγμα σε αυτό το παράθυρο / πλαίσιο",
target_parent:"Άνοιγμα στο γονικό παράθυρο / πλαίσιο",
target_top:"Άνοιγμα στο πιο επάνω πλαίσιο (αντικαθιστά όλα τα άλλα πλαίσια)",
target_blank:"Άνοιγμα σε νέο παράθυρο",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Όνομα παραθύρου",
popup_return:"Εισαγωγή 'return false'",
popup_scrollbars:"Εμφάνιση γραμμών κύλισης",
popup_statusbar:"Εμφάνιση γραμμής κατάστασης",
popup_toolbar:"Εμφάνιση εργαλειοθήκης",
popup_menubar:"Εμφάνιση γραμμής μενού",
popup_location:"Εμφάνιση γραμμής διεύθυνσης",
popup_resizable:"Κάνε το παράθυρο μη σταθερό",
popup_dependent:"Εξαρτάται (Mozilla/Firefox μόνο)",
popup_size:"Μέγεθος",
popup_position:"Θέση (X/Y)",
id:"Μοναδική ταυτότητα (Id)",
style:"Στύλ",
classes:"Κλάσσεις",
target_name:"Όνομα στόχου",
langdir:"Κατεύθυνση κειμένου",
target_langcode:"Γλώσσα στόχου",
langcode:"Κωδικός γλώσσας",
encoding:"Κωδικοποίηση χαρακτήρων στόχου",
mime:"Τύπος MIME στόχου",
rel:"Συσχέτιση σελίδας με στόχο",
rev:"Συσχέτιση στόχου με σελίδα",
tabindex:"Δείκτης καρτέλας",
accesskey:"Κλειδί πρόσβασης",
ltr:"Αριστερά προς δεξιά",
rtl:"Δεξιά προς αριστερά",
link_list:"Λίστα συνδέσμων"
});