tinyMCE.addI18n('el.xhtmlxtras_dlg',{
attribute_label_title:"Τίτλος",
attribute_label_id:"Μοναδική ταυτότητα (ID)",
attribute_label_class:"Κλάσση",
attribute_label_style:"Στύλ",
attribute_label_cite:"Αναφορά",
attribute_label_datetime:"Ημερομηνία/Ώρα",
attribute_label_langdir:"Κατεύθυνση κειμένου",
attribute_option_ltr:"Αριστερά προς δεξιά",
attribute_option_rtl:"Δεξιά προς αριστερά",
attribute_label_langcode:"Γλώσσα",
attribute_label_tabindex:"Δείκτης καρτέλας",
attribute_label_accesskey:"Κλειδί πρόσβασης",
attribute_events_tab:"Γεγονότα",
attribute_attrib_tab:"Ιδιότητες",
general_tab:"Γενικά",
attrib_tab:"Ιδιότητες",
events_tab:"Γεγονότα",
fieldset_general_tab:"Γενικές ρυθμίσεις",
fieldset_attrib_tab:"Ιδιότητες στοιχείων",
fieldset_events_tab:"Γεγονότα στοιχείων",
title_ins_element:"Στοιχείο εισαγωγής",
title_del_element:"Στοιχείο διαγραφής",
title_acronym_element:"Στοιχείο ακρωνυμίου",
title_abbr_element:"Στοιχείο συντόμευσης",
title_cite_element:"Στοιχείο αναφοράς",
remove:"Απόσυρση",
insert_date:"Εισαγωγή ημερομηνίας/ώρας",
option_ltr:"Αριστερά προς δεξιά",
option_rtl:"Αριστερά προς δεξιά",
attribs_title:"Εισαγωγή/Επεξεργασία ιδιοτήτων"
});