tinyMCE.addI18n('el.media_dlg',{
title:"Εισαγωγή / Επεξεργασία ενσωματωμένων πολυμέσων",
general:"Γενικά",
advanced:"Για προχωρημένους",
file:"Αρχείο/URL",
list:"Λίστα",
size:"Διαστάσεις",
preview:"Προεπισκόπηση",
constrain_proportions:"Διατήρηση αναλογίας πλάτους/ύψους",
type:"Τύπος",
id:"Μοναδική ταυτότητα (Id)",
name:"Όνομα",
class_name:"Κλάσση",
vspace:"Κάθετο κενό",
hspace:"Οριζόντιο κενό",
play:"Αυτόματη αναπαραγωγή",
loop:"Επανάληψη",
menu:"Προβολή μενού",
quality:"Ποιότητα",
scale:"Μεγέθυνση",
align:"Στοίχιση",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Υπόβαθρο",
base:"Βάση",
flashvars:"Ρυθμίσεις Flash",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Hidden",
controller:"Controller",
kioskmode:"Kiosk mode",
playeveryframe:"Play every frame",
targetcache:"Target cache",
correction:"No correction",
enablejavascript:"Ενεργοποίηση JavaScript",
starttime:"Start time",
endtime:"End time",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Target",
volume:"Volume",
autostart:"Auto start",
enabled:"Enabled",
fullscreen:"Fullscreen",
invokeurls:"Invoke URLs",
mute:"Mute",
stretchtofit:"Stretch to fit",
windowlessvideo:"Windowless video",
balance:"Balance",
baseurl:"Base URL",
captioningid:"Captioning id",
currentmarker:"Current marker",
currentposition:"Current position",
defaultframe:"Default frame",
playcount:"Play count",
rate:"Rate",
uimode:"UI Mode",
flash_options:"Επιλογές Flash",
qt_options:"Επιλογές Quicktime",
wmp_options:"Επιλογές Windows media player",
rmp_options:"Επιλογές Real media player",
shockwave_options:"Επιλογές Shockwave",
autogotourl:"Auto goto URL",
center:"Center",
imagestatus:"Image status",
maintainaspect:"Maintain aspect",
nojava:"No java",
prefetch:"Prefetch",
shuffle:"Shuffle",
console:"Console",
numloop:"Αρ επαναλήψεων",
controls:"Controls",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Sound",
progress:"Progress",
qtsrc:"QT Src",
qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
align_top:"Επάνω",
align_right:"Δεξιά",
align_bottom:"Κάτω",
align_left:"Αριστερά",
align_center:"Κέντρο",
align_top_left:"Επάνω δεξιά",
align_top_right:"Επάνω αριστερά",
align_bottom_left:"Κάτω αριστερά",
align_bottom_right:"Κάτω δεξιά",
flv_options:"Flash video options",
flv_scalemode:"Τύπος μεγέθυνσης",
flv_buffer:"Buffer",
flv_startimage:"Start image",
flv_starttime:"Start time",
flv_defaultvolume:"Default volumne",
flv_hiddengui:"Hidden GUI",
flv_autostart:"Αυτόματη αναπαραγωγή",
flv_loop:"Επανάληψη",
flv_showscalemodes:"Show scale modes",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});