editAreaLoader.lang["el"]={
new_document: "νέο άδειο έγγραφο",
search_button: "εύρεση και αντικατάσταση",
search_command: "αναζήτηση επομένου / άνοιγμα περιοχής αναζήτησης",
search: "αναζ/ση",
replace: "αντικ/σταση",
replace_command: "αντικατάσταση / άνοιγμα περιοχής αναζήτησης",
find_next: "εύρεση επομ.",
replace_all: "αντικατ. όλων",
reg_exp: "regular expressions",
match_case: "ταίριασμα πεζών εφαλαίων",
not_found: "δεν βρέθηκε.",
occurrence_replaced: "περιπτώσεις αντικαταστάθηκαν.",
search_field_empty: "Πεδίο αναζήτησης κενό",
restart_search_at_begin: "Έφτασε στο τέλος της περιοχής αναζήτησης. Ξεκίνημα από την αρχή.",
move_popup: "μετακίνηση παραθύρουν αναζήτησης",
font_size: "--Μέγεθος--",
go_to_line: "μετακίνηση στη γραμμή",
go_to_line_prompt: "μετακίνηση στον αρ. γραμμής:",
undo: "ακύρωση",
redo: "αναίρεση ακύρωσης",
change_smooth_selection: "ενεργοποίηση/απενεργοποίηση χαρακτηριστικών εμφάνισης (πιο ολοκληρωμένη εμφάνιση περισσότερος όγκος εργασίας για τον υπολογιστή σας)",
highlight: "φωτεινή σύνταξη ενεργή/ανενεργή",
reset_highlight: "αρχικοποίηση της φωτεινής σύνταξης (εάν έχει αποσυγχρονιστεί)",
word_wrap: "εναλλαγή της αναδίπλωσης λέξεων",
help: "σχετικά",
save: "αποθήκευση",
load: "'ανοιγμα",
line_abbr: "Γρ.",
char_abbr: "Χαρ.",
position: "Θέση",
total: "Σύνολο",
close_popup: "κλείσιμο παραθύρου",
shortcuts: "Συντομεύσεις",
add_tab: "προσθήκη (tab) στήλης στο κείμενο",
remove_tab: "αφαίρεση (tab) στήλης από το κείμενο",
about_notice: "Σημείωση: Η λειτουργία φωτεινότητας αφορά μικρά κείμενα",
toggle: "Εναλλαγή επεξεργαστή κειμένου",
accesskey: "Πλήκτρο πρόσβασης",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Επεξεργασία...",
fullscreen: "Πλήρης οθόνη",
syntax_selection: "--Σύνταξη--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_smarty: "Smarty",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
syntax_java: "Java",
close_tab: "Κλείσιμο αρχείου"
};
