tinyMCE.addI18n('el.style_dlg',{
title:"Επεξεργασία στύλ CSS",
apply:"Εφαρμογή",
text_tab:"Κείμενο",
background_tab:"Υπόβαθρο",
block_tab:"Τμήμα",
box_tab:"Κουτί",
border_tab:"Περιθώριο",
list_tab:"Λίστα",
positioning_tab:"Θέση",
text_props:"Κείμενο",
text_font:"Γραμματοσειρά",
text_size:"Μέγεθος",
text_weight:"Βάρος",
text_style:"Στύλ",
text_variant:"Μεταβολή",
text_lineheight:"Ύψος γραμμής",
text_case:"Περίπτωση",
text_color:"Χρώμα",
text_decoration:"Διακόσμηση",
text_overline:"επιγράμμιση",
text_underline:"υπογράμμιση",
text_striketrough:"διαγράμμιση",
text_blink:"αναβόσμημα",
text_none:"κανένα",
background_color:"Χρώμα υπόβαθρου",
background_image:"Χρώμα εικόνας",
background_repeat:"Επανάληψη",
background_attachment:"Επισύναψη",
background_hpos:"Οριζόντια θέση",
background_vpos:"Κάθετη θέση",
block_wordspacing:"Διάκενο λέξεων",
block_letterspacing:"Διάκενο χαρακτήρων",
block_vertical_alignment:"Κάθετη στοίχηση",
block_text_align:"Στοίχιση κειμένου",
block_text_indent:"Εσοχή κειμένου",
block_whitespace:"Κενά",
block_display:"Εμφάνιση",
box_width:"Πλάτος",
box_height:"Ύψος",
box_float:"Μετακινούμενο",
box_clear:"Καθάρισμα",
padding:"Διάκενο",
same:"Το ίδιο για όλα",
top:"Επάνω",
right:"Αριστερά",
bottom:"Κάτω",
left:"Δεξιά",
margin:"Περιθώριο",
style:"Στύλ",
width:"Πλάτος",
height:"Ύψος",
color:"Χρώμα",
list_type:"Τύπος",
bullet_image:"Εικόνα κουκκίδας",
position:"Θέση",
positioning_type:"Τύπος",
visibility:"Ορατότητα (visibility)",
zindex:"Βάθος (z-index)",
overflow:"Υπερχείλιση (overflow)",
placement:"Τοποθεσία (placement)",
clip:"Κλιπ"
});